# Generated by Django 5.0.6 on 2024-06-25 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('shop', '0003_rename_product_table_product_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_tb')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product_tb')),
            ],
        ),
    ]
