# Generated by Django 5.0.6 on 2024-06-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_cart_table'),
        ('shop', '0003_rename_product_table_product_tb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart_table',
            new_name='cart_tb',
        ),
    ]
