# Generated by Django 5.0.6 on 2024-06-25 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_cart_table_cart_tb'),
        ('shop', '0003_rename_product_table_product_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('order_date', models.CharField(max_length=20)),
                ('order_time', models.CharField(max_length=20)),
                ('grandtotal', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_tb')),
            ],
        ),
        migrations.CreateModel(
            name='oderitems_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_tb')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product_tb')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.order_table')),
            ],
        ),
    ]
