# Generated by Django 5.0.6 on 2024-06-25 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_order_table_oderitems_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=20)),
                ('cardnumber', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=20)),
                ('expiary_date', models.CharField(max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_tb')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.order_table')),
            ],
        ),
    ]
