# Generated by Django 5.0.6 on 2024-06-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_table',
            new_name='product_tb',
        ),
    ]
